### ISSUE TITLE
Manjaro.org Website scrolls to the right side?

### ISSUE THREAD

**Issue by zohairajmal** [manjaro/manjaro.github.io#1]
When I side scroll the website with the laptops touch pad, it shows an empty white pane. It may be related to some padding/margin issue on the website? Image attached : [https://imgur.com/a/Ic8Cnei](url)

**Comment by oberon-manjaro** [comment]
Thank you for you report.
Our code is now hosted on gitlab.manjaro.org
Could you kindly open an issue [**here**](https://gitlab.manjaro.org/tools/maintenance-tools/manjaro-homepage/issues), thank you.
