### ISSUE TITLE
Pagination? and 'Archives' page may be?

### ISSUE THREAD

**Issue by fingli** [manjaro/manjaro.github.io#10]
Currently all post are shown on the index page. After a time it will make site-loading slow and it is not necessary to scroll that long page in order to read some old post. We can set pagination i.e. to make Jekyll to serve posts on multiple pages. 
On this regard, we can make also a page "archives" where all post could be listed. 

I made a mirror here https://fingli.github.io/ - see how the pagination looks like and how it works. Archives are still in the process :) at the time of writing this I haven't uploaded it yet.

**Comment by philmmanjaro** [comment]
Great catch. If you have something to change that fact, I'm happy about it.

**Comment by philmmanjaro** [comment]
I checked your demo page. Seems to work just fine. Create a merge request so we update the main page.

**Comment by fingli** [comment]
Done :) 
For some reason in these pull requests Github shows my synchronization commits as new, but I hope it will not broke the code.
