### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by fingli** [manjaro/manjaro.github.io#16]
Guys, you publish like crazy recently :) 
As the number of post increases so are the pages, the list of pages soon will exceed the text area. We need some other solution, something which could show pages relatively. May be something like this? 
https://github.com/timble/jekyll-pagination

**Comment by philmmanjaro** [comment]
Would be an idea. However we are soon to release our new homepage layout to the public. There we have our own blog software created. Also the forum and other parts are based on our own webpage framework developed by [desertbit](http://desertbit.com).

**Comment by philmmanjaro** [comment]
If you have time, please implement it to the current code. I'm currently busy with some installer development ...

**Comment by fingli** [comment]
Their own website is "coming soon" :) 
That will be better. A standalone CMS will be good solution with such amount of content that Manjaro's website has already. In a long term Jekyll will get narrower and narrower, I'm almost sure that even currently writing is not a pleasant experience. 

OK, I will test that code how it works locally. At a glance seems not  a big trouble - replacing the current pagination code and some CSS styling may be.

**Comment by philmmanjaro** [comment]
Well, it took us two years to develop this new framework. DesertBit will use Manjaro as a reference. Hence the CEO of DesertBit is also the founder of Manjaro Linux - what better example would it be to promote our own software with our own distribution. Our current sourcecode can be found also on [github](https://github.com/desertbit). So feel free to prepare a merge request for our current temp. github page of Manjaro. Thx for all the support so far with our current layout. Helped me a lot to concentrate on other things ;)
