### ISSUE TITLE
Add RSS feed

### ISSUE THREAD

**Issue by gunar** [manjaro/manjaro.github.io#18]
There's an [easy way](https://github.com/snaptortoise/jekyll-rss-feeds/blob/master/feed.xml) to implement rss feed in jekyll websites.

We could then link this to Twitter -- which is what I really want: Manjaro's news in my Twitter feed.

If guys OK this, I can PR, but I hear there's a new website coming. Should I even bother?

Thank you all for this awesome piece of software. I love manjaro <3

**Comment by philmmanjaro** [comment]
Create a PR for this. We are updating our homepage but for now it would be good to use all given options. When the new homepage is there we will have a rss feed anyway.
