### ISSUE TITLE
New version of 'Jekyll Now'

### ISSUE THREAD

**Issue by fingli** [manjaro/manjaro.github.io#22]
A new version of "Jekyll Now" has been released earlier in March due to the updates of **Jekyll** itself: https://github.com/barryclark/jekyll-now/releases/tag/v1.2.0
As I can see there are not significant changes and the old "Jekyll Now" theme works well with Manjaro website so far, but the new version has some code improvements. It will be better if we update the Manjaro's blog as well, to prevent bugs appearing in the future (if any). It has to be done 'manually' i.e only those changes which not affect the content or the look of the main website
I'm thinking of something like comparing the files one to another and applying changes accordingly.

**Comment by philmmanjaro** [comment]
https://github.com/manjaro/manjaro.github.io/commit/b5ec5df69399f5484d4e7bd2c4376621c8656340

**Comment by philmmanjaro** [comment]
Seems to work now with v1.2.0 after some tweaking ;)

**Comment by fingli** [comment]
There are two additional 'things' which need some fix:
- in Download page the SHA1 sums are too large
- in footer GitHub icon is black-on-black

**Comment by fingli** [comment]
#23
