### ISSUE TITLE
[Capella] consider to remove 15.12 install medias

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/manjaro.github.io#24]
Since we are now needing the new **pacman 5.0.1** for the hooks, it would make sense to remove the outdated **15.12** install medias from our download page. Else we have to mark very prominent that installing the new **pacman** release is needed before installing any other package.

**Comment by Kirek** [comment]
I'm okay with it.
A few months ago you asked me to review the inclusion of kdepim in the kde profile, well applications 16.04 has been released and the situation hasn't changed: 200mb+ extra of ram consumption at boot without opening any application. So now kdepim gone and added thunderbird-kde.
https://github.com/manjaro/manjaro-tools-iso-profiles/commit/52bf69b0472386a19ad27509b9712f91e24346d9
Everything else should be fine.

**Comment by oberon2007** [comment]
Could installing pacman fist not be done with majaro-system for now?
Or what install medias would you then recommend people download? Just pre3?
The manjaro-system solution would be helpful of course also for all the community editions pre pacman 5 that are still out there!

**Comment by oberon2007** [comment]
Actually there are some [more packages](https://github.com/manjaro/packages-community/pull/165#issuecomment-215490590) that need to be up-to-date to for all the hooks to be present!

**Comment by philmmanjaro** [comment]
With **manjaro-system** this will mean we add **pacman** again to be synced first. Would be also a solution for it. But this must be tested on a fresh **15.12** install to see it as an option.
