### ISSUE TITLE
Partitioning /usr boot issue

### ISSUE THREAD

**Issue by RamMat84** [manjaro/manjaro.github.io#25]
Hi all,
When partitioning /usr to another partition, the system won't boot.
It seem that it is because the root partition is mounted and then trying to run /bin/init which is a symlink to /usr/bin/init, and it is not mounted yet...

**Comment by philmmanjaro** [comment]
This is the bugtracker of the home-page on **github**. Do you have any issue with it? I assume you have some problems with one of our installers. Which is it? **thus**, **calamares** or **cli-installer**?
