### ISSUE TITLE
More descriptive page about different editions

### ISSUE THREAD

**Issue by badbodh** [manjaro/manjaro.github.io#28]
Right now 'download' page doesn't say much about individual editions. It will be helpful to add a screenshot, and brief description (like you do on the Release Announcements). Highlight the flagship editions and community editions. Importantly, have all info in one place.
For example Korora's website shows a list of available editions
![screenshot_2016-06-03_22-13-42](https://cloud.githubusercontent.com/assets/17335519/15785999/e25b54d4-29d7-11e6-898c-75bbfe95b027.png)
Then we go to dedicated webpage for the cinnamon edition
![screenshot_2016-06-03_22-15-22](https://cloud.githubusercontent.com/assets/17335519/15786047/186c3d22-29d8-11e6-92d0-ba8a0aec743a.png)

Along with some fancy description
1. mention included packages by pointing to the respective iso-profile on github
2. mention third-party repos (if any) added
3. caveats and disclaimers

This way, a newcomer will be able to comfortably decide which edition to pick and why.

**Comment by philmmanjaro** [comment]
Well, I already started some [spartan version](http://manjaro.github.io/download-community/) as a work in progress. However we won't want to encourage people to use community editions as of now.

**Comment by badbodh** [comment]
Well, people do find out about community editions and jump in without concern. Hence the 3 points I mentioned above need to be told, especially the caveats and disclaimers. That should make them think twice.

**Comment by oberon2007** [comment]
I've been working on it [a little more](http://manjaro.github.io/download-community/) and added some links to the respective forum threads
