### ISSUE TITLE
where is manjaro's main issue tracker?

### ISSUE THREAD

**Issue by c0b** [manjaro/manjaro.github.io#31]
I'm new user of manjaro Since 16.06, want to report new bug while the main site https://manjaro.github.io/ is not telling where is entry of bug tracker? if just using github, which repo is the main entrance? because I'm not sure which repo should it belong to under this github organization

**Comment by philmmanjaro** [comment]
For now we are using **github** and users should post the depending repositories. If the package is not listed in one of our packages then it is maitained by **Archlinux** itself. What issue would you like to post?

**Comment by c0b** [comment]
have filed manjaro/manjaro-tools-iso-profiles#164 but there are more issues with this distro

relying on github issue tracker's main problem is there are multiple entrances under this github org, even worse is some repos got deprecated (like manjaro/manjaroiso#48 why not delete); this keeps confusing people don't know where to file issues

More issues I found is with displaying, maybe in driver, because some specific portion of the screen is flashing, intermittently I compared same hardware running Ubuntu 16.04 doesn't have the problem, should I record a small video to describe ? I am running live iso mode, more details I have written in https://github.com/manjaro/manjaro-tools-iso-profiles/issues/164#issuecomment-229496352

**Comment by c0b** [comment]
I see https://manjaro.org/2016/07/24/manjaro-has-now-a-new-bugtracker/ and https://bugs.manjaro.org/ is a nice move; this can be closed now.
