### ISSUE TITLE
New look

### ISSUE THREAD

**Issue by fingli** [manjaro/manjaro.github.io#7]
What do you think about this layout?

![new_layout](https://cloud.githubusercontent.com/assets/420475/8124921/4d4b6b0c-10e9-11e5-9f74-928184d6fc17.png)
The differences with the current are: 
* Site name - "Manjaro Linux" uses font Comfortaa, to adhere original logo
* Hyperlinks in green color
* Green strip bellow the header, just for a complementary color to the black&white current layout  

No additional files needed, only some code tweaks.

**Comment by philmmanjaro** [comment]
Well, please open a merge request for these changes. Don't change any font as those might not be installed on non-Manjaro systems. Everything else is fine with me.

**Comment by fingli** [comment]
OK, sure. I haven't made any fork yet :) I just wanted an opinion first. Don't worry about the font, it will be linked from Google API as it is current Lato font. The user experience will not be affected.

**Comment by philmmanjaro** [comment]
Ah ok. Then go for it.

**Comment by philmmanjaro** [comment]
If you on it, maybe you can also create a nice Download-Page for our install medias. Currently they are located here:

http://sourceforge.net/projects/manjarotest/files/
http://sourceforge.net/projects/manjarolinux/files/

Maybe just for latest release and current development versions. For other we can link still to sourceforge ...

**Comment by fingli** [comment]
I will try to. :)

**Comment by fingli** [comment]
Damn, I think I pressed wrong button
